site_name: "Persona Link"
site_dir: './docs'

theme:
  name: "material"

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          allow_inspection: true
          show_source: false
          show_root_heading: false
    enable_inventory: false

- monorepo

nav:
  - Intro: 'index.md'
  - Library: '!include ./persona_link/mkdocs.yml'
  - Server: '!include ./server/mkdocs.yml'
  - Widgets: '!include ./widgets/mkdocs.yml'