site_name: "Persona Link"
docs_dir: './docs_src'
site_dir: './docs'

theme:
  name: "material"

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          summary: false
          allow_inspection: true
          show_source: false
          show_root_heading: false
          show_inheritance_diagram: true
          show_root_toc_entry: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          enable_inventory: false
          show_bases: false
          modernize_annotations: true

- monorepo

nav:
  - Intro: 'index.md'
  - Library: '!include ./persona_link/mkdocs.yml'
  - Server: '!include ./server/mkdocs.yml'
  - Widgets: '!include ./widgets/mkdocs.yml'